#!/usr/bin/env bash
#Accepts 4 parameters
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses

if [ $# -lt 3 ];
echo
"0-transfer_file PATH_TO_SSH_KEY";
    exit;
fi;


