#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

#Requirements:

#The redirection must be a “301 Moved Permanently”
#You answer file should be a Bash script containing co

sudo apt-get -y update

sudo ufw allow 'Nginx HTTP'

#project 0x0C

sudo sed -i /redirect_me https://www.youtube.com/ permanent;

#task web serve
