#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

#Requirements:

#The page must return an HTTP 404 error code
#The page must contain the string Ceci n'est pas une page
#Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

echo "Ceci n'est pas une page"
#task 4 

sed -i "46i error_page 404 /custom_404.html

#contain the string Ceci n'est pas une page
service nginx restart
