#!/usr/bin/env bash
#Docker container, I curl the port 8080 mapped to the Docker container port 80, it does not return a page but an error message. 


echo "ServerName localhost" >> /etc/apache2.conf

#web stack debigging 
service apache2 start
