#!/usr/bin/env bash
#configure it to our needs so that you can connect to a server without typing a password.
Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school

# configured to use the private key ~/.ssh/school
#Your SSH client configuration must be configured to refuse to authenticate using a password
